import re

INPUT_FILE = "extracted_metadata.txt"
OUTPUT_TEX = "gallery.tex"

def parse_and_generate():
    with open(INPUT_FILE, "r") as f:
        content = f.read()
    

    # Split by "id='sample-" which we know exists in the file
    chunks = content.split("id='sample-")
    # chunks[0] is header garbage
    
    latex_output = "\\subsection{Qualitative Gallery}\nThe following pages present a selection of generated captions compared to the ground truth.\n\n"
    
    valid_samples = 0
    seen_ids = set()
    
    for chunk in chunks[1:]: # Skip first chunk
        # Chunk starts with "0'>... " or "12'>..."
        # Extract ID
        try:
            # Take string until next quote or angle bracket
            id_str = chunk.split("'")[0]
            sample_id = int(id_str)
        except:
            continue
            
        if sample_id in seen_ids:
            continue
        seen_ids.add(sample_id)
            
        if sample_id > 15:
            continue
            
        print(f"Processing Sample {sample_id}")
        
        # Extract Ground Truth
        gt_match = re.search(r"Ground truth:</div>\s*<div class='caption-text'>(.*?)</div>", chunk, re.DOTALL)
        if not gt_match:
             gt_match = re.search(r"class='ground-truth'>Ground truth:</div>.*?class='caption-text'>(.*?)</div>", chunk, re.DOTALL)
        
        gt_text = gt_match.group(1).strip() if gt_match else "TEXT NOT FOUND"
        
        # Extract Generated Caption (SPE+Qwen2-7b v2)
        gen_text = "N/A"
        if "SPE+Qwen2-7b" in chunk:
            gen_match = re.search(r"SPE\+Qwen2-7b.*?<div class='caption-text'>(.*?)</div>", chunk, re.DOTALL)
            if gen_match:
                 gen_text = gen_match.group(1).strip()
            else:
                 if "caption-text error" in chunk:
                     gen_text = "[Empty Caption generated by Model]"

        # Clean up text
        def clean_tex(t):
            t = t.replace("&quot;", '"').replace("&#x27;", "'").replace("&amp;", "&")
            chars = {
                '%': '\\%',
                '$': '\\$',
                '#': '\\#',
                '_': '\\_',
                '{': '\\{',
                '}': '\\}',
            }
            return "".join(chars.get(c, c) for c in t)

        gt_text = clean_tex(gt_text)
        gen_text = clean_tex(gen_text)
        
        # Generate LaTeX
        latex_output += "\\clearpage\n"
        latex_output += "\\begin{figure}[p]\n"
        latex_output += "    \\centering\n"
        latex_output += f"    \\includegraphics[width=0.8\\textwidth]{{figures/sample_{sample_id}.png}}\n"
        latex_output += f"    \\caption[Sample {sample_id}]" + "{\\textbf{Sample " + str(sample_id) + "}. \\\\\n"
        latex_output += f"    \\textbf{{Ground Truth}}: {gt_text} \\\\\n"
        latex_output += f"    \\textbf{{Generated (SPE+Qwen)}}: {gen_text}}}\n"
        latex_output += f"    \\label{{fig:gallery_{sample_id}}}\n"
        latex_output += "\\end{figure}\n"
        
        valid_samples += 1

    with open(OUTPUT_TEX, "w") as f:
        f.write(latex_output)
    print(f"Generated gallery.tex with {valid_samples} samples.")

if __name__ == "__main__":
    parse_and_generate()
